In [9]:
## Importing Libraries

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf 
validation_set = tf.keras.utils.image_dataset_from_directory(
    'New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 6912 files belonging to 15 classes.


In [20]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf  # Import TensorFlow here

training_set = tf.keras.utils.image_dataset_from_directory(
    'New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 27647 files belonging to 15 classes.


In [21]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break                                  #pixels of each image

tf.Tensor(
[[[[129.   114.   119.  ]
   [121.   106.   111.  ]
   [130.5  113.5  119.5 ]
   ...
   [ 95.25  80.25  87.25]
   [ 91.5   76.5   83.5 ]
   [104.    89.    96.  ]]

  [[131.   116.   121.  ]
   [127.5  112.5  117.5 ]
   [134.   117.   123.  ]
   ...
   [ 99.75  84.75  91.75]
   [111.25  96.25 103.25]
   [109.25  94.25 101.25]]

  [[124.5  109.5  114.5 ]
   [127.25 112.25 117.25]
   [127.75 110.75 116.75]
   ...
   [107.25  92.25  99.25]
   [ 93.    78.    85.  ]
   [ 93.75  78.75  85.75]]

  ...

  [[181.75 170.75 176.75]
   [194.75 183.75 189.75]
   [182.5  171.5  177.5 ]
   ...
   [124.   113.   121.  ]
   [156.5  145.5  153.5 ]
   [108.5   97.5  105.5 ]]

  [[183.25 172.25 178.25]
   [191.75 180.75 186.75]
   [182.5  171.5  177.5 ]
   ...
   [115.5  104.5  112.5 ]
   [116.75 105.75 113.75]
   [132.   121.   129.  ]]

  [[182.   171.   177.  ]
   [183.   172.   178.  ]
   [174.25 163.25 169.25]
   ...
   [135.5  124.5  132.5 ]
   [130.5  119.5  127.5 ]
   [127.75 116.75 12

In [22]:
### to avoid overshooting
#1. choose small learning rate default is 0.001 we are taking 0.0001
#2. there may be chance of underfitting , so increase number of neuron (means unable to capture entire info of data set) 
#3. Add more convolution layer to extract more feature from images there may be possibility that model unable to capture relevant feature or lack of feature so feed with more feature

In [23]:
## Building Model
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout,Input
from tensorflow.keras.models import Sequential

In [24]:
input_layer = Input(shape=[128, 128, 3])
model = Sequential()
model.add(input_layer)

In [25]:

# Convolutional layers with ReLU activation and MaxPooling
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))  # Removed input_shape
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))  # Removed input_shape
model.add(MaxPool2D(pool_size=2, strides=2))

In [26]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [27]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [28]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [29]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [30]:
model.add(Dropout(0.25))                             #to avoid the problem of over fitting

In [31]:
##flattening operation: 2D to 1D 
model.add(Flatten())

In [32]:
model.add(Dense(units=1500,activation='relu'))

In [33]:
model.add(Dropout(0.4))

In [34]:
#Output Layer
model.add(Dense(units=15,activation='softmax'))

In [35]:
## compiling model               extracted features in summary
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_10 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_12 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_15 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_16 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_17 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_18 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_19 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │        22,515 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,808,239 (29.79 MB)

 Trainable params: 7,808,239 (29.79 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
## Underfitting (too few epochs): If you use too few epochs, the model might not be exposed to the training data enough times to learn the underlying relationships effectively. This can lead to underfitting, where the model performs poorly on both training and validation data.
## Overfitting (too many epochs): Conversely, with too many epochs, the model might start to memorize the specific patterns in the training data and lose its ability to generalize to unseen data. This phenomenon is called overfitting
training_history2 = model.fit(x=training_set,validation_data=validation_set,epochs=5)


Epoch 1/5
  8/864 ━━━━━━━━━━━━━━━━━━━━ 45:06 3s/step - accuracy: 0.0599 - loss: 2.7681

In [1]:
train_loss, train_acc = cnn.evaluate(training_set)
print('Training accuracy:', train_acc)

NameError: name 'cnn' is not defined

In [ ]:
print(train_loss,train_acc)

In [ ]:
val_loss,val_acc = model.evaluate(validation_set)

In [ ]:
print(val_loss,train_loss)

In [ ]:
##saving the model

model.save("trained_model.keras")

In [ ]:
## recording history

import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)

In [ ]:
epochs = [i for i in range(1,6)]
plt.plot(epochs,training_history2.history['accuracy'],color ='red', label='Training Accuracy')
plt.plot(epochs,training_history2.history['val_accuracy'],color ='blue', label='Validation Accuracy')
plt.xlabel("no of epochs")
plt.ylabel("accuracy result")
plt.legend()
plt.show()

In [ ]:
#some other matrics for model evaluation

In [ ]:
class_name = validation_set.class_names
class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

In [ ]:
y_pred = model.predict(test_set)
y_pred,y_pred.shape

In [ ]:
predicted_categories= tf.argmax(y_pred,axis=1)


In [ ]:
predicted_categories

In [ ]:
true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

In [ ]:
y_true = tf.argmax(true_categories,axis=1)
y_true

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_true,predicted_categories,target_names=class_name))

In [ ]:
cn = confusion_matrix(y_true,predicted_categories)
cn

In [ ]:
plt.figure(figsize=(40,40))
sns.heatmap(cn,annot=True,annot_kws={'size':10})
plt.xlabel("predicted class",fontsize=20)
plt.ylabel("actual class",fontsize=20)
plt.title("confusion matrix ",fontsize=25)
plt.show()
